### ISSUE TITLE
This doesn't build anymore

### ISSUE THREAD

**Issue by robbieh** [bnewbold/exuberant-hacks#1]
Is there any intention to carry it forward?
```
error[E0642]: patterns aren't allowed in functions without bodies
   --> /home/robbie/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.3.19/src/serialize.rs:147:45
    |
147 | ...                   &f_name: &str,
    |                       ^^^^^^^ pattern not allowed in function without body

error[E0503]: cannot use `state` because it was mutably borrowed
    --> /home/robbie/.cargo/registry/src/github.com-1ecc6299db9ec823/getopts-0.2.14/src/lib.rs:1008:25
     |
955  |     let mut machine = |cont: &mut bool, (i, c): (usize, char)| {
     |                       ---------------------------------------- borrow of `state` occurs here
...
959  |         state = match (state, whitespace, limit) {
     |         ----- borrow occurs due to use of `state` in closure
...
1008 |     while cont && match state { B | C => true, A => false } {
     |                         ^^^^^ use of borrowed `state`
1009 |         machine(&mut cont, (fake_i, ' '));
     |         ------- borrow later used here

For more information about this error, try `rustc --explain E0503`.
error: could not compile `getopts` due to previous error
warning: build failed, waiting for other jobs to finish...
For more information about this error, try `rustc --explain E0642`.
error: build failed
```

**Comment by bnewbold** [comment]
Interesting... I would have hoped that the `Cargo.lock` file would have been stickier, but the `Cargo.toml` dependencies seem to have been incoherent, so i'm surprised that it ever worked.

I pushed a small update to the dependencies, can you give that a try? It compiled and the binary ran for me on Debian bullseye / amd64. I didn't try running under xscreensaver.

I am unlikely to maintain or continue this project, mostly because the `glutin` hacks to work with an existing X11 window should be up-streamed and I don't know enough about X11, glutin, or GUI windowing generally to push that through.

You are, of course, welcome to fork or re-use the name or whatever, the more bouncing bovines the better!

**Comment by robbieh** [comment]
Hey! It builds and runs now! Thank you for making the update. I knew I wouldn't have time to dig in and figure it out anytime soon.

Though I appreciate XScreenSaver, I've been trying to add a hack to it for awhile now. But coding in C is so much drudgery that I have had a hard time making progress.

I know a bit about X11 and have done a little work with piston/glutin. If I'm successful with making a new hack here, perhaps I'll push the project forward. Thanks much :)

**Comment by robbieh** [comment]
Just FYI - it appears the glutin now allows drawing on existing window. I'll play with that this weekend.

https://github.com/rust-windowing/glutin/pull/1058
